"""initial tables: users, cargos, cargo_photos

Revision ID: 439c55d1aaa1
Revises: 
Create Date: 2026-09-14 05:01:49.441725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '439c55d1aaa1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('loading_region', sa.String(length=30), nullable=False),
    sa.Column('loading_district', sa.String(length=255), nullable=True),
    sa.Column('loading_landmark', sa.String(length=500), nullable=True),
    sa.Column('loading_lat', sa.Float(), nullable=True),
    sa.Column('loading_lon', sa.Float(), nullable=True),
    sa.Column('unloading_region', sa.String(length=30), nullable=False),
    sa.Column('unloading_district', sa.String(length=255), nullable=True),
    sa.Column('unloading_landmark', sa.String(length=500), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('loading_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargos_loading_region'), 'cargos', ['loading_region'], unique=False)
    op.create_index(op.f('ix_cargos_owner_id'), 'cargos', ['owner_id'], unique=False)
    op.create_index(op.f('ix_cargos_status'), 'cargos', ['status'], unique=False)
    op.create_index(op.f('ix_cargos_unloading_region'), 'cargos', ['unloading_region'], unique=False)
    op.create_index(op.f('ix_cargos_vehicle_type'), 'cargos', ['vehicle_type'], unique=False)
    op.create_table('cargo_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargo_photos_cargo_id'), 'cargo_photos', ['cargo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cargo_photos_cargo_id'), table_name='cargo_photos')
    op.drop_table('cargo_photos')
    op.drop_index(op.f('ix_cargos_vehicle_type'), table_name='cargos')
    op.drop_index(op.f('ix_cargos_unloading_region'), table_name='cargos')
    op.drop_index(op.f('ix_cargos_status'), table_name='cargos')
    op.drop_index(op.f('ix_cargos_owner_id'), table_name='cargos')
    op.drop_index(op.f('ix_cargos_loading_region'), table_name='cargos')
    op.drop_table('cargos')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
