"""add load_type, driver_offers table

Revision ID: 50a267e9bcaa
Revises: 439c55d1aaa1
Create Date: 2026-09-14 06:10:00.367087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a267e9bcaa'
down_revision: Union[str, None] = '439c55d1aaa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('departure_region', sa.String(length=30), nullable=False),
    sa.Column('departure_district', sa.String(length=255), nullable=True),
    sa.Column('departure_landmark', sa.String(length=500), nullable=True),
    sa.Column('departure_lat', sa.Float(), nullable=True),
    sa.Column('departure_lon', sa.Float(), nullable=True),
    sa.Column('destination_region', sa.String(length=30), nullable=True),
    sa.Column('destination_district', sa.String(length=255), nullable=True),
    sa.Column('destination_landmark', sa.String(length=500), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=20), nullable=False),
    sa.Column('load_type', sa.String(length=20), server_default='qisman_yuk', nullable=False),
    sa.Column('available_weight', sa.Float(), nullable=True),
    sa.Column('available_volume', sa.Float(), nullable=True),
    sa.Column('price_expectation', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_type', sa.String(length=20), nullable=True),
    sa.Column('departure_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_offers_departure_region'), 'driver_offers', ['departure_region'], unique=False)
    op.create_index(op.f('ix_driver_offers_destination_region'), 'driver_offers', ['destination_region'], unique=False)
    op.create_index(op.f('ix_driver_offers_driver_id'), 'driver_offers', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_offers_load_type'), 'driver_offers', ['load_type'], unique=False)
    op.create_index(op.f('ix_driver_offers_status'), 'driver_offers', ['status'], unique=False)
    op.create_index(op.f('ix_driver_offers_vehicle_type'), 'driver_offers', ['vehicle_type'], unique=False)
    op.add_column('cargos', sa.Column('load_type', sa.String(length=20), server_default='toliq_mashina', nullable=False))
    op.create_index(op.f('ix_cargos_load_type'), 'cargos', ['load_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cargos_load_type'), table_name='cargos')
    op.drop_column('cargos', 'load_type')
    op.drop_index(op.f('ix_driver_offers_vehicle_type'), table_name='driver_offers')
    op.drop_index(op.f('ix_driver_offers_status'), table_name='driver_offers')
    op.drop_index(op.f('ix_driver_offers_load_type'), table_name='driver_offers')
    op.drop_index(op.f('ix_driver_offers_driver_id'), table_name='driver_offers')
    op.drop_index(op.f('ix_driver_offers_destination_region'), table_name='driver_offers')
    op.drop_index(op.f('ix_driver_offers_departure_region'), table_name='driver_offers')
    op.drop_table('driver_offers')
    # ### end Alembic commands ###
